[project]
name = "minicpm"
version = "0.1.0"
requires-python = ">=3.10, <3.13"
dependencies = [
    "onnxruntime~=1.20.1",
    "onnxruntime-gpu~=1.20.1",
    "torch~=2.5.1",
    "torchaudio~=2.5.1",
    "torchvision~=0.20.0",
]
