default:
  logger:
    log_level: "INFO"
  service:
    host: "0.0.0.0"
    port: 8282
    cert_file: "ssl_certs/localhost.crt"
    cert_key: "ssl_certs/localhost.key"
  chat_engine:
    model_root: "models"
    handler_search_path:
      - "src/handlers"
    handler_configs:
      RtcClient:
        module: client/rtc_client/client_handler_rtc
        concurrent_limit: 1
      SileroVad:
        module: vad/silerovad/vad_handler_silero
        speaking_threshold: 0.5
        start_delay: 2048
        end_delay: 5000
        buffer_look_back: 5000
        speech_padding: 512
      SenseVoice:
        enabled: True
        module: asr/sensevoice/asr_handler_sensevoice
        model_name: "iic/SenseVoiceSmall"
      Edge_TTS:
        enabled: True
        module: tts/edgetts/tts_handler_edgetts
        voice: "en-US-AriaNeural"
      LLM_Bailian:
        enabled: True
        module: llm/openai_compatible/llm_handler_openai_compatible
        model_name: "gpt-4o-mini"
        enable_video_input: True # ensure your llm support video input
        # model_name: "gemini-2.0-flash"
        system_prompt: "You are QUARI, an AI assistant with vision capabilities. You can see through the camera in real-time. When users ask about what you can see, or ask questions like 'can you see', 'do you see', 'what's there', 'describe the image/video', or similar visual questions, actively describe what you observe in the camera feed. Be helpful and descriptive about the visual content, objects, scenes, and activities you can see. Describe like you would phisicaly see it, not like it's a picture. Respond in English, keep answers concise but informative. Provide answers like human would say."
        api_url: "https://api.openai.com/v1"
        # api_url: 'http://127.0.0.1:11434/v1' # ollama
        # api_url: 'https://generativelanguage.googleapis.com/v1beta/openai/'
        api_key: "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"
      LiteAvatar:
        module: avatar/liteavatar/avatar_handler_liteavatar
        avatar_name: 20250408/sample_data
        fps: 25
        debug: false
        enable_fast_mode: false
        use_gpu: true
