default:
  logger:
    log_level: "INFO"
  service:
    host: "0.0.0.0"
    port: 8282
  chat_engine:
    model_root: "models"
    handler_search_path:
      - "src/handlers"
    handler_configs:
      RtcClient:
        enabled: False
        module: client/rtc_client/client_handler_rtc
      # Enable MiniCPM for local LLM (no API key needed)
      MiniCPM:
        enabled: True
        module: llm/minicpm/llm_handler_minicpm
        model_name: "MiniCPM-o-2_6"
        system_prompt: "You are a helpful AI assistant. Keep your responses concise and conversational."
      # Enable EdgeTTS for speech synthesis (no API key needed)
      EdgeTTS:
        enabled: True
        module: tts/edgetts/tts_handler_edge_tts
        voice: "en-US-JennyNeural"
      # Enable MuseTalk avatar (if models are available)
      AvatarMusetalk:
        enabled: True
        module: avatar/musetalk/avatar_handler_musetalk
        fps: 20
        batch_size: 2
        avatar_video_path: "src/handlers/avatar/musetalk/MuseTalk/data/video/yongen.mp4"
        avatar_model_dir: "models/musetalk/avatar_model"
        force_create_avatar: false
        debug: false
      # Enable VAD for voice detection
      SileroVad:
        enabled: True
        module: vad/silerovad/vad_handler_silero
        speaking_threshold: 0.5
        start_delay: 2048
        end_delay: 5000
        buffer_look_back: 5000
        speech_padding: 512
      # Enable SenseVoice for speech recognition
      SenseVoice:
        enabled: True
        module: asr/sensevoice/asr_handler_sensevoice
        model_name: "iic/SenseVoiceSmall"
